import type { RawDesignTokens, RawTypographyToken } from '../design-md.types.js';

function quote(value: string | number): string {
  return typeof value === 'number' ? String(value) : `'${value.replaceAll("'", "\\'")}'`;
}

function renderValueGroup(entries: Record<string, string | number>, indent: string): string[] {
  return Object.entries(entries).map(([name, value]) => `${indent}'${name}': { value: ${quote(value)} },`);
}

function renderTextStyles(entries: Record<string, RawTypographyToken>, indent: string): string[] {
  const lines: string[] = [];
  for (const [name, style] of Object.entries(entries)) {
    const props = Object.entries(style)
      .filter(([, value]) => value !== undefined)
      .map(([prop, value]) => `${prop}: ${quote(value as string | number)}`)
      .join(', ');
    lines.push(`${indent}'${name}': { value: { ${props} } },`);
  }
  return lines;
}

/**
 * Generate a `tokens.gen.ts` fragment from DESIGN.md tokens for a PandaCSS
 * project. The generated file is spread into `panda.config.ts` by the user —
 * the config itself is never edited in place:
 *
 * ```ts
 * import { designMdTokens, designMdTextStyles } from './tokens.gen';
 * export default defineConfig({
 *   theme: { extend: { tokens: designMdTokens, textStyles: designMdTextStyles } },
 * });
 * ```
 */
export function writePandacssTokensFile(tokens: RawDesignTokens): string {
  const lines: string[] = [
    '/**',
    ' * GENERATED by `genx design sync --push` from DESIGN.md — do not edit.',
    ' * Spread into panda.config.ts:',
    ' *   theme: { extend: { tokens: designMdTokens, textStyles: designMdTextStyles } }',
    ' */',
    '',
    'export const designMdTokens = {',
  ];

  if (tokens.colors && Object.keys(tokens.colors).length > 0) {
    lines.push('  colors: {', ...renderValueGroup(tokens.colors, '    '), '  },');
  }
  if (tokens.rounded && Object.keys(tokens.rounded).length > 0) {
    lines.push('  radii: {', ...renderValueGroup(tokens.rounded, '    '), '  },');
  }
  if (tokens.spacing && Object.keys(tokens.spacing).length > 0) {
    lines.push('  spacing: {', ...renderValueGroup(tokens.spacing, '    '), '  },');
  }
  lines.push('} as const;', '');

  lines.push('export const designMdTextStyles = {');
  if (tokens.typography && Object.keys(tokens.typography).length > 0) {
    lines.push(...renderTextStyles(tokens.typography, '  '));
  }
  lines.push('} as const;', '');

  return lines.join('\n');
}
