import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { extractThemeBlocks, parseCustomProperties } from '../extractors/tailwind4.extractor.js';
import { writePandacssTokensFile } from './pandacss.writer.js';
import { writeTailwind4Theme } from './tailwind4.writer.js';

const FIXTURES = join(fileURLToPath(new URL('.', import.meta.url)), '../../../../test/fixtures/design-md');
const TW4_CSS = readFileSync(join(FIXTURES, 'tailwind4-project/src/app.css'), 'utf8');

describe('writeTailwind4Theme', () => {
  it('rebuilds owned namespaces and preserves everything else', () => {
    const updated = writeTailwind4Theme(TW4_CSS, {
      colors: { primary: '#111111', accent: '#b8422e' },
      rounded: { md: '10px' },
      spacing: { base: '0.25rem' },
    });
    expect(updated).not.toBeNull();
    const block = extractThemeBlocks(updated ?? '')[0] ?? '';
    const props = parseCustomProperties(block);

    // Owned namespaces fully rebuilt from tokens.
    expect(props['color-primary']).toBe('#111111');
    expect(props['color-accent']).toBe('#b8422e');
    expect(props['color-secondary']).toBeUndefined();
    expect(props['radius-md']).toBe('10px');
    expect(props['radius-sm']).toBeUndefined();
    expect(props['spacing']).toBe('0.25rem');
    expect(props['spacing-gutter']).toBeUndefined();

    // Unowned properties survive.
    expect(props['shadow-card']).toBe('0 1px 3px rgb(0 0 0 / 0.1)');
    expect(props['font-sans']).toBe("'Public Sans', sans-serif");
    expect(props['text-base']).toBe('1rem');

    // CSS outside the block survives.
    expect(updated).toContain('color: var(--color-primary);');
  });

  it('returns null when no @theme block exists', () => {
    expect(writeTailwind4Theme('body { color: red; }', { colors: { primary: '#000' } })).toBeNull();
  });

  it('is idempotent', () => {
    const tokens = { colors: { primary: '#111111' }, rounded: { md: '10px' } };
    const once = writeTailwind4Theme(TW4_CSS, tokens);
    const twice = writeTailwind4Theme(once ?? '', tokens);
    expect(twice).toBe(once);
  });
});

describe('writePandacssTokensFile', () => {
  it('generates a spreadable tokens fragment', () => {
    const generated = writePandacssTokensFile({
      colors: { 'primary': '#1a1c1e', 'brand-500': '#2665fd' },
      rounded: { md: '8px' },
      spacing: { md: '16px' },
      typography: { 'body-md': { fontFamily: 'Inter', fontSize: '16px', fontWeight: 400 } },
    });
    expect(generated).toContain('GENERATED by `genx design sync --push`');
    expect(generated).toContain("'primary': { value: '#1a1c1e' },");
    expect(generated).toContain("'brand-500': { value: '#2665fd' },");
    expect(generated).toContain('radii: {');
    expect(generated).toContain(
      "'body-md': { value: { fontFamily: 'Inter', fontSize: '16px', fontWeight: 400 } },",
    );
  });
});
