import { existsSync } from 'node:fs';
import { cp, readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { execa } from 'execa';
import type { MonorepoSource } from './monorepo.source.js';

export interface CloneStarterOptions {
  /** SSH clone URL of the starter repository. */
  repoUrl: string;
  /** Tag to clone. Never a branch — generation must be reproducible. */
  tag: string;
  /** Absolute path the starter is cloned into. */
  targetDir: string;
}

/**
 * Shallow-clone the monorepo starter at a pinned tag, then detach it from the starter's history so
 * the generated repository starts with its own.
 */
export async function cloneStarter({ repoUrl, tag, targetDir }: CloneStarterOptions): Promise<void> {
  try {
    await execa('git', ['clone', '--depth', '1', '--branch', tag, repoUrl, targetDir]);
  } catch (error) {
    throw new Error(
      [
        `Failed to clone ${repoUrl} at tag ${tag}.`,
        `Verify the tag exists:  git ls-remote --tags ${repoUrl}`,
        'and that your SSH key has access to the repository.',
        '',
        error instanceof Error ? error.message : String(error),
      ].join('\n'),
      { cause: error },
    );
  }

  await rm(join(targetDir, '.git'), { recursive: true, force: true });
}

/**
 * Directories never copied from a local starter checkout. `node_modules` and build output would be
 * enormous and are regenerated by install anyway; `.git` and `.turbo` belong to the source repo.
 */
const LOCAL_COPY_EXCLUDES = new Set(['node_modules', '.git', '.turbo', 'dist']);

/**
 * Copy a local starter checkout, working tree and all.
 *
 * Uncommitted changes are copied deliberately — generating from a local path exists so starter
 * changes can be tried out before they are committed or tagged.
 */
export async function copyLocalStarter(sourceDir: string, targetDir: string): Promise<void> {
  if (!existsSync(join(sourceDir, 'package.json'))) {
    throw new Error(
      `No package.json at ${sourceDir}. Set monorepoStarter.path to a monorepo-starter checkout.`,
    );
  }

  await cp(sourceDir, targetDir, {
    recursive: true,
    filter: (source) => {
      const relative = source.slice(sourceDir.length + 1);
      const [first] = relative.split('/');
      return !first || !LOCAL_COPY_EXCLUDES.has(first);
    },
  });

  await removeNestedBuildOutput(targetDir);
}

/**
 * Strip build output from workspace members.
 *
 * The top-level copy filter only matches first path segments, so `apps/server/dist` and
 * `packages/ui/node_modules` come through untouched.
 */
async function removeNestedBuildOutput(targetDir: string): Promise<void> {
  for (const group of ['apps', 'packages']) {
    const groupDir = join(targetDir, group);
    if (!existsSync(groupDir)) continue;

    const members = await readdir(groupDir, { withFileTypes: true });
    await Promise.all(
      members
        .filter((member) => member.isDirectory())
        .flatMap((member) =>
          [...LOCAL_COPY_EXCLUDES].map((junk) =>
            rm(join(groupDir, member.name, junk), { recursive: true, force: true }),
          ),
        ),
    );
  }
}

/** Materialise the starter into `targetDir` from whichever source was resolved. */
export async function materializeStarter(
  source: MonorepoSource,
  repoUrl: string,
  targetDir: string,
): Promise<void> {
  if (source.kind === 'local') {
    return copyLocalStarter(source.path, targetDir);
  }

  return cloneStarter({ repoUrl, tag: source.tag, targetDir });
}
